export type ValueCommunicationType
    = 'VOICE LINE UP'
    | 'VOICE LINE LEFT'
    | 'VOICE LINE RIGHT'
    | 'VOICE LINE DOWN'
    | 'EMOTE UP'
    | 'EMOTE LEFT'
    | 'EMOTE RIGHT'
    | 'EMOTE DOWN'
    | 'ULTIMATE STATUS'
    | 'HELLO'
    | 'NEED HEALING'
    | 'GROUP'
    | 'THANKS'
    | 'ACKNOWLEDGE'